### ISSUE TITLE
[UI] 更新admin保存成功的提示方式

### ISSUE THREAD

**Issue by klbjlabs** [maodouio/meteor-react-redux-base#6]
- @cf41ccd
- 移除meteor的jquery包
- 添加了 npm jquery包
- 将一部分保存成功信息提示方式改为用 toastr 插件来呈现，发布文章，发布活动等需要路由跳转的界面不变

效果
![image](https://cloud.githubusercontent.com/assets/4111893/19590765/17fbe900-97a6-11e6-9b92-a0c6179f7e8e.png)

**Comment by klbjlabs** [comment]
已完成修改

**Comment by limingth** [comment]
@klbjlabs  这个成功信息提示方式，出现位置放在上面或者旁边，体验是不是更好一些

**Comment by klbjlabs** [comment]
@limingth 我看看能不能做出来右侧弹出的效果吧，这个是默认的效果比较难看
