### ISSUE TITLE
Thoughts on adding meteor-react-router-ssr? 

### ISSUE THREAD

**Issue by Morganjackson** [maodouio/meteor-react-redux-base#9]
Have you given any thought to adding ``meteor-react-router-ssr``?

  https://github.com/thereactivestack/meteor-react-router-ssr

Ideally you would only use it for the public routes but I'm not sure if thats possible.

**Comment by lhz516** [comment]
Hi, at the beginning we considered to use SSR for shortering first loading time. However we use Webpack to do code splitting, user will only download necessary code bundle. If we add `meteor-react-router-ssr` for existing code, the entire architecture will be changed. Maybe we will want to add SSR for other usages in the future. Anyway, thanks for giving us this suggestion!

**Comment by Morganjackson** [comment]
Ok thanks! great project by the way.
